name: 'Create release notes'

on:
  workflow_dispatch:
  # TODO: update to monthly
  
env:
  CHANGELOG: changelog.md
  TEMPLATE: release-notes-template.md
  MONTH: 5 # TODO: update to current month
  YEAR: 2025 # TODO: update to current year
  

jobs: 
  job1:
    name: 'Generate release notes'
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install Python packages
        run: |
          pip install datetime
          pip install datefinder
      - name: Generate release notes
        run: |
          python3 generate-release-notes.py $MONTH $YEAR 
          git add release-notes.md
      - name: Open pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: add release notes
          title: Add release notes for ${{ env.MONTH }} ${{ env.YEAR }}
          body: Add release notes to reflect release changes
          branch: add-release-notes
          base: main

  
          