name: 'Create release notes'

on:
  workflow_dispatch:
  # TODO: update to monthly
  
env:
  CHANGELOG: changelog.md
  TEMPLATE: release-notes-template.md
  MONTH: 5 # TODO: update to current month
  YEAR: 2025 # TODO: update to current year
  

jobs: 
  job1:
    name: 'Prepare'
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: install-python-packages
        run: |
          pip install datetime
          pip install datefinder
      - name: generate-release-notes
        run: |
          python3 generate-release-notes.py $MONTH $YEAR 
      - uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release-notes.md
          retention-days: 1
  
          